/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.116
 * Generated at: 2026-05-04 09:39:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/bvign/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1774522045186L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>VM-Code IDE | Login</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile responsive -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --bg-dark: #000000;\r\n");
      out.write("            --bg-card: rgba(20, 20, 25, 0.7);\r\n");
      out.write("            --text-primary: #ffffff;\r\n");
      out.write("            --text-secondary: #a1a1aa;\r\n");
      out.write("            --primary-accent: #a855f7;\r\n");
      out.write("            --gradient-text: linear-gradient(135deg, #ffffff 0%, #a855f7 100%);\r\n");
      out.write("            --border-color: rgba(255, 255, 255, 0.15);\r\n");
      out.write("            --font-family: 'Outfit', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: var(--font-family);\r\n");
      out.write("            background: var(--bg-dark);\r\n");
      out.write("            background-image:\r\n");
      out.write("                radial-gradient(circle at 15% 50%, rgba(168, 85, 247, 0.15) 0%, transparent 50%),\r\n");
      out.write("                radial-gradient(circle at 85% 30%, rgba(255, 255, 255, 0.05) 0%, transparent 50%);\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            background: var(--bg-card);\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            padding: 3rem 2.5rem;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 450px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.6), 0 0 25px rgba(168, 85, 247, 0.1);\r\n");
      out.write("            animation: fadeInUp 0.8s ease-out;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0) 100%);\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header h2 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            letter-spacing: -1px;\r\n");
      out.write("            background: var(--gradient-text);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header p {\r\n");
      out.write("            color: var(--text-secondary);\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin-bottom: 2.5rem;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-group {\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-group input {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem 1.2rem;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            outline: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            font-family: var(--font-family);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-group input:focus {\r\n");
      out.write("            border-color: var(--primary-accent);\r\n");
      out.write("            box-shadow: 0 0 15px rgba(168, 85, 247, 0.2);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: var(--primary-accent);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            font-family: var(--font-family);\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submit-btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(168, 85, 247, 0.4);\r\n");
      out.write("            background: #b266ff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error-msg {\r\n");
      out.write("            color: #ef4444;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            background: rgba(239, 68, 68, 0.1);\r\n");
      out.write("            padding: 0.75rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid rgba(239, 68, 68, 0.2);\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-link {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            color: var(--text-secondary);\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-link a {\r\n");
      out.write("            color: var(--primary-accent);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .register-link a:hover {\r\n");
      out.write("            color: #c084fc;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeInUp {\r\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 1.5rem 0;\r\n");
      out.write("            color: var(--text-secondary);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider::before,\r\n");
      out.write("        .divider::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            border-bottom: 1px solid var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider:not(:empty)::before {\r\n");
      out.write("            margin-right: .8em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .divider:not(:empty)::after {\r\n");
      out.write("            margin-left: .8em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .github-btn {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("            color: var(--text-primary);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-family: var(--font-family);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .github-btn:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .login-container {\r\n");
      out.write("                padding: 2.5rem 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"login-container\">\r\n");
      out.write("    <div class=\"login-header\">\r\n");
      out.write("        <h2>Welcome Back</h2>\r\n");
      out.write("        <p>Login to your VM-Code account</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"post\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <input type=\"text\" name=\"loginId\" placeholder=\"Email or Username\" required/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("            <input type=\"password\" name=\"password\" placeholder=\"Password\" required/>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <button type=\"submit\" class=\"submit-btn\">Login</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"divider\">OR</div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ide\" class=\"github-btn\">\r\n");
      out.write("        <svg height=\"24\" width=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"margin-right: 12px;\">\r\n");
      out.write("            <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("            <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("        </svg>\r\n");
      out.write("        Continue as Guest\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"register-link\">\r\n");
      out.write("        Don't have an account? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\">Register</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/login.jsp(246,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        <div class=\"error-msg\" style=\"display: block;\">\r\n");
          out.write("            Invalid username or password\r\n");
          out.write("        </div>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
